### ISSUE TITLE
Presentar el nombre en mayúsculas

### ISSUE THREAD

**Issue by lelepompom** [lelepompom/IWVG.SwC.SandraOrtega#2]
Para la clase User: [Presentar el nombre en mayúsculas](https://github.com/lelepompom/IWVG.SwC.SandraOrtega/wiki#presentar-el-nombre-en-may%C3%BAsculas)

**Comment by jolomoreno** [comment]
Hola, tengo una duda, con qué formato quieres que cree mi rama de desarrollo? Si no tenías ninguna forma pensada, puedo utilizar el formato issue#XX

**Comment by lelepompom** [comment]
Hola Jose! Al ser éste el ticket #2, habría que crear desde "develop" la rama "issue#2"

**Comment by jolomoreno** [comment]
Okey, muchas gracias!

**Comment by jolomoreno** [comment]
Acabo de realizar la implementación del issue, está mergeada mi rama local con develop en local. Además, he subido los cambios de develop en local a origin/develop. Procedo a cerrar la tarea.
