### ISSUE TITLE
Incluir el método menor

### ISSUE THREAD

**Issue by lelepompom** [lelepompom/IWVG.SwC.SandraOrtega#3]
Para la clase DecimalCollection: [Incluir el método menor](https://github.com/lelepompom/IWVG.SwC.SandraOrtega/wiki#incluir-el-m%C3%A9todo-menor)

**Comment by albertogarciag95** [comment]
Done!

**Comment by lelepompom** [comment]
Buenas,

Reabro la issue para mejorar la clase DecimalCollection. Actualmente se lanza hasta 3 veces el literal 'Empty collection' en las excepciones. Este literal se podría definir en una constante para evitar repetirlo a lo largo del código. 

Cualquier cosa, me dices. Gracias!

**Comment by albertogarciag95** [comment]
Hecho! Vuelvo a mover a la issue a Done.
Un saludo
