### ISSUE TITLE
Incluir los métodos isPropia e isImpropia

### ISSUE THREAD

**Issue by lelepompom** [lelepompom/IWVG.SwC.SandraOrtega#4]
Para la clase Fraction: [Incluir los métodos isPropia e isImpropia](https://github.com/lelepompom/IWVG.SwC.SandraOrtega/wiki#incluir-los-m%C3%A9todos-ispropia-e-isimpropia)

**Comment by jolomoreno** [comment]
Acabo de realizar la implementación del issue, está mergeada mi rama local con develop en local. Además, he subido los cambios de develop en local a origin/develop. Procedo a cerrar la tarea.
