### ISSUE TITLE
Fix issue#4

### ISSUE THREAD

**Issue by lelepompom** [lelepompom/IWVG.SwC.SandraOrtega#7]
_

> Replace this if-then-else statement by a single return statement.

_

El test de sonar ha marcado un 'code-smell' en los métodos isPropia() e isImpropia() por no cubrirlos del todo con el test.

- Una solución podría ser devolver solo una sentencia "return (this.numerator > this.denominator) ? true : false;"
- Otra solución, crear el test que cubra el caso que falta.

**Comment by jolomoreno** [comment]
Corregido fix, se ha solucionado con una operación ternaria y un solo return.

**Comment by jolomoreno** [comment]
Vuelvo a abrir la issue para no tener que hacer mas ramas, he corregido los metodos isPropia e isImpropia para que devuelva directamente la condicion < ó > respectivamente.
En Travis CI se han pasado correctamente todos los test, confírmame que Sonar no da problemas y cerramos esta issue definitivamente.
Muchas gracias, un saludo!

**Comment by lelepompom** [comment]
Ya ha quedado solucionada la cobertuba del test para los métodos, Sonar no da ningún tipo de error en ellas, así que damos esta issue por cerrada. Gracias Jose!
